// Generated by CoffeeScript 2.2.4
(function() {
    /*
      Rudimentary code for creating groups of students randomly for our ICS 465 and ICS 665 courses.
      Note: The text in table this app created can be easily pasted into as sheet on our Drive which then can be pasted
        into the assignments document.
      Obviously, there should be possible to generate the groups in a sheeet directly using Google App Script, or even
      generate the table in a document, but this would need quite some expertise in App Script and it's UI...

      Copyright 2/2020 Jan Stelovsky, UH Manoa ICS
      MIT license: Use any way you please, just don't complain...
    */
    var clone, groupSize;

    // Shuffles this array. Must be called on the array
    // Returns the changed array
    // Probably the simplest useful algorithm...
    // Note: '@' in CS translates to 'this.' in JS
    Array.prototype.shuffle = function() { // '::' translates to '.prototype.' - see the corresponding js file
        var i, j;
        i = this.length;
        // for all array indices i except the 0th going backwards
        while (i > 1) {
            // get random index in [0..i]
            j = Math.floor(Math.random() * i--);
            // switch items i and j; note that exchanging
            [this[i], this[j]] = [this[j], this[i]];
        }
        return this;
    };




}).call(this);


